
[main]
default_scenario=0
max_thread=4
use_max_cpu=true
config_filename="settings.toml"
max_filesize=120

[networking]
limit_traffic_rate=300

[virtualfs]
max_capacity=1024
max_file_counts=20000

[log]
filename="droidcat.log"

[packages]
limit_minimum_supported_api="KitKat"

[input]
default_input="droidcat.apk"

[output]
unknown_output=["app-out", "out", "package"]

[plugins]
[modules]
